<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>WinExe</OutputType>
		<TargetFrameworks>net9.0-windows;net10.0-windows</TargetFrameworks>
		<UseWindowsForms>true</UseWindowsForms>
		<ApplicationIcon>Resources\as.ico</ApplicationIcon>
		<Copyright>Copyright © Escartem 2024-2026; Copyright © yarik0chka 2024-2025; Copyright © Hashblen 2024-2025; Copyright © Razmoth 2022-2024; Copyright © Perfare 2018-2022</Copyright>
		<DebugType>embedded</DebugType>
		<RuntimeIdentifier>win-x64</RuntimeIdentifier>
		<AppendRuntimeIdentifierToOutputPath>false</AppendRuntimeIdentifierToOutputPath>
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\AnimeStudio.Utility\AnimeStudio.Utility.csproj" />
		<ProjectReference Include="..\AnimeStudio\AnimeStudio.csproj" />
	</ItemGroup>

	<ItemGroup>
		<EmbeddedResource Update="Properties\Resources.resx">
			<Generator>ResXFileCodeGenerator</Generator>
			<LastGenOutput>Resources.Designer.cs</LastGenOutput>
		</EmbeddedResource>
		<Compile Update="Properties\Resources.Designer.cs">
			<AutoGen>True</AutoGen>
			<DependentUpon>Resources.resx</DependentUpon>
			<DesignTime>True</DesignTime>
		</Compile>
		<Compile Update="Properties\Settings.Designer.cs">
		  <DesignTimeSharedInput>True</DesignTimeSharedInput>
		  <AutoGen>True</AutoGen>
		  <DependentUpon>Settings.settings</DependentUpon>
		</Compile>
	</ItemGroup>

	<ItemGroup>
		<ContentWithTargetPath Include="..\AnimeStudio.Libraries\AnimeStudio.Ooz.dll">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
			<TargetPath>AnimeStudio.Ooz.dll</TargetPath>
		</ContentWithTargetPath>
		<ContentWithTargetPath Include="..\AnimeStudio.Libraries\AnimeStudio.FBXNative.dll">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
			<TargetPath>AnimeStudio.FBXNative.dll</TargetPath>
		</ContentWithTargetPath>
		<ContentWithTargetPath Include="..\AnimeStudio.Libraries\AnimeStudio.HLSLDecompiler.dll">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
			<TargetPath>AnimeStudio.HLSLDecompiler.dll</TargetPath>
		</ContentWithTargetPath>
		<ContentWithTargetPath Include="..\AnimeStudio.Libraries\AnimeStudio.ACL.DB.dll">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
			<TargetPath>AnimeStudio.ACL.DB.dll</TargetPath>
		</ContentWithTargetPath>
		<ContentWithTargetPath Include="..\AnimeStudio.Libraries\AnimeStudio.ACL.SR.dll">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
			<TargetPath>AnimeStudio.ACL.SR.dll</TargetPath>
		</ContentWithTargetPath>
		<ContentWithTargetPath Include="..\AnimeStudio.Libraries\AnimeStudio.ACL.ZZZ.dll">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
			<TargetPath>AnimeStudio.ACL.ZZZ.dll</TargetPath>
		</ContentWithTargetPath>
		<ContentWithTargetPath Include="..\LICENSE">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
			<TargetPath>LICENSE</TargetPath>
		</ContentWithTargetPath>
	</ItemGroup>

	<ItemGroup>
		<ContentWithTargetPath Include="..\AnimeStudio.Libraries\x86\fmod.dll">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
			<TargetPath>x86\fmod.dll</TargetPath>
		</ContentWithTargetPath>
		<ContentWithTargetPath Include="..\AnimeStudio.Libraries\x64\fmod.dll">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
			<TargetPath>x64\fmod.dll</TargetPath>
		</ContentWithTargetPath>
	</ItemGroup>

	<ItemGroup>
		<ContentWithTargetPath Include="..\AnimeStudio.Libraries\x86\acl.dll">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
			<TargetPath>x86\acl.dll</TargetPath>
		</ContentWithTargetPath>
		<ContentWithTargetPath Include="..\AnimeStudio.Libraries\x64\acl.dll">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
			<TargetPath>x64\acl.dll</TargetPath>
		</ContentWithTargetPath>
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="MessagePack" Version="3.1.7" />
		<PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
		<PackageReference Include="OpenTK" Version="4.9.4" />
		<PackageReference Include="OpenTK.GLControl" Version="4.0.2" />
        <PackageReference Include="System.Drawing.Common" Version="10.0.9"/>
	</ItemGroup>

	<ItemGroup>
	  <None Update="Properties\Settings.settings">
	    <Generator>SettingsSingleFileGenerator</Generator>
	    <LastGenOutput>Settings.Designer.cs</LastGenOutput>
	  </None>
	</ItemGroup>

	<Target Name="RemoveSkiaSharpPdb" AfterTargets="ResolveAssemblyReferences;Build">
		<ItemGroup>
			<NativePdbFiles Include="$(OutDir)*.pdb" />
			<NativePdbFiles Include="$(PublishDir)*.pdb" Condition="'$(PublishDir)' != ''" />
		</ItemGroup>
		<Delete Files="@(NativePdbFiles)" />
	</Target>

</Project>
